# Generated by Django 6.0 on 2025-12-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio_short',
            field=models.CharField(blank=True, help_text='Short bio/tagline', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether catalyst is currently accepting requests'),
        ),
    ]
