# Generated by Django 6.0 on 2025-12-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_bio_short_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='portfolio_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('SEEKER', 'Seeker'), ('CATALYST', 'Catalyst')], default='SEEKER', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specializations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='style_goals',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
